# Generated by Django 3.0.6 on 2022-05-19 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signupvcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=4)),
                ('phone_last_five_digits', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=6)),
                ('will_expire_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '인증 번호',
                'verbose_name_plural': '인증 번호(들)',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '휴대전화 번호',
                'verbose_name_plural': '휴대전화 번호(들)',
            },
        ),
    ]
