# Generated by Django 3.0.6 on 2022-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupvcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='signupvcode',
            name='phone_last_digit',
            field=models.CharField(max_length=4),
        ),
    ]
