# Generated by Django 3.0.6 on 2022-05-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20220515_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupvcode',
            name='will_expire_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
