# Generated by Django 3.0.6 on 2022-05-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_signupvcode_will_expire_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupvcode',
            name='phone_last_digit',
        ),
        migrations.AddField(
            model_name='signupvcode',
            name='last_name',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupvcode',
            name='phone_last_five_digits',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
