# Generated by Django 3.0.6 on 2021-07-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checknissue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': '인증 코드', 'verbose_name_plural': '인증 코드(들)'},
        ),
    ]
