# Generated by Django 3.0.6 on 2022-02-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checknissue', '0002_auto_20210707_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checklist',
            new_name='Issuecert',
        ),
    ]
