# Generated by Django 3.0.6 on 2022-02-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checknissue', '0003_auto_20220202_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuecert',
            options={'verbose_name': '얼럼나이 인증 코드', 'verbose_name_plural': '얼럼나이 인증 코드(들)'},
        ),
    ]
