# Generated by Django 3.0.6 on 2022-02-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checknissue', '0004_auto_20220202_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuecert',
            options={'verbose_name': '인증 코드', 'verbose_name_plural': '인증 코드(들)'},
        ),
    ]
