# Generated by Django 3.0.6 on 2021-07-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0002_auto_20210703_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applymembership',
            name='failed',
        ),
    ]
