# Generated by Django 3.0.6 on 2021-07-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0004_applymembership_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymembership',
            name='plan',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='plan_len',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='portfolio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='reason_len',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='self_intro',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='self_intro_len',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='tracking',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='tracking_etc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='tracking_reference',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='wanted_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
