# Generated by Django 3.0.6 on 2021-07-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0010_auto_20210705_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('미결정', '미결정'), ('미선발', '미선발'), ('선발', '선발')], default='미결정', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='plan',
            field=models.TextField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='reason',
            field=models.TextField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='self_intro',
            field=models.TextField(blank=True, max_length=510, null=True),
        ),
    ]
