# Generated by Django 3.0.6 on 2021-07-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0012_auto_20210705_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymembership',
            name='wanted_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
