# Generated by Django 3.0.6 on 2021-07-07 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applynsubmit', '0013_applymembership_wanted_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applymembership',
            options={'verbose_name': '지원서', 'verbose_name_plural': '지원서(들)'},
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('미결정', '미결정'), ('미선발', '미선발'), ('선발', '선발')], default='미결정', max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='ApplymembershipNoti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wanted_id', models.CharField(blank=True, max_length=36, null=True)),
                ('wanted_title', models.CharField(blank=True, max_length=50, null=True)),
                ('passed', models.TextField(blank=True, max_length=510, null=True)),
                ('failed', models.TextField(blank=True, max_length=510, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '통보 메일',
                'verbose_name_plural': '통보 메일(들)',
            },
        ),
    ]
