# Generated by Django 3.0.6 on 2021-07-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0017_auto_20210707_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applymembershipnoti',
            old_name='failed',
            new_name='failed_content',
        ),
        migrations.RenameField(
            model_name='applymembershipnoti',
            old_name='passed',
            new_name='passed_content',
        ),
        migrations.RemoveField(
            model_name='applymembershipnoti',
            name='applicant',
        ),
        migrations.AddField(
            model_name='applymembershipnoti',
            name='saved_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='applymembershipnoti',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
