# Generated by Django 3.0.6 on 2021-07-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0023_auto_20210707_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applymembershipnoti',
            name='saved_at',
        ),
        migrations.RemoveField(
            model_name='applymembershipnoti',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='applymembershipnoti',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('미선발', '미선발'), ('선발', '선발'), ('미결정', '미결정')], default='미결정', max_length=5, null=True),
        ),
    ]
