# Generated by Django 3.0.6 on 2021-07-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0025_auto_20210708_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymembership',
            name='will_be_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applymembershipnoti',
            name='will_be_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('미결정', '미결정'), ('미선발', '미선발'), ('선발', '선발')], default='미결정', max_length=5, null=True),
        ),
    ]
