# Generated by Django 3.0.6 on 2021-07-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0027_auto_20210709_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymembership',
            name='code',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('미결정', '미결정'), ('미선발', '미선발'), ('선발', '선발')], default='미결정', max_length=5, null=True),
        ),
    ]
