# Generated by Django 3.0.6 on 2022-02-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0033_auto_20210812_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applymembershipwithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(max_length=4)),
                ('phone_last', models.CharField(max_length=4)),
                ('email_host', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '블루무버 인증 코드',
                'verbose_name_plural': '블루무버 인증 코드(들)',
            },
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('미결정', '미결정'), ('미선발', '미선발'), ('선발', '선발')], default='미결정', max_length=5, null=True),
        ),
    ]
