# Generated by Django 3.0.6 on 2022-02-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0035_auto_20220202_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applymembershipwithdrawal',
            options={'verbose_name': '인증 코드', 'verbose_name_plural': '인증 코드(들)'},
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('미결정', '미결정'), ('선발', '선발'), ('미선발', '미선발')], default='미결정', max_length=5, null=True),
        ),
    ]
