# Generated by Django 3.0.6 on 2022-02-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0038_auto_20220218_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('선발', '선발'), ('미결정', '미결정'), ('미선발', '미선발')], default='미결정', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applymembershipwithdrawalqueue',
            name='email',
            field=models.CharField(max_length=500),
        ),
    ]
