# Generated by Django 3.0.6 on 2022-02-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0041_auto_20220218_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymembershipwithdrawalqueue',
            name='period',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applymembershipwithdrawalqueue',
            name='phone',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('선발', '선발'), ('미선발', '미선발'), ('미결정', '미결정')], default='미결정', max_length=5, null=True),
        ),
    ]
