# Generated by Django 3.0.6 on 2022-02-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0043_auto_20220218_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymembershipwithdrawalqueue',
            name='datetime',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('미선발', '미선발'), ('미결정', '미결정'), ('선발', '선발')], default='미결정', max_length=5, null=True),
        ),
    ]
