# Generated by Django 3.0.6 on 2022-02-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0046_auto_20220220_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplymembershipwithdrawalQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=100)),
                ('activities', models.CharField(max_length=300)),
                ('data_boolean', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=1000)),
                ('will_be_deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '탈퇴 신청자',
                'verbose_name_plural': '탈퇴 신청자(들)',
            },
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('선발', '선발'), ('미결정', '미결정'), ('미선발', '미선발')], default='미결정', max_length=5, null=True),
        ),
    ]
