# Generated by Django 3.0.6 on 2022-02-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0049_auto_20220221_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymembershipwithdrawalqueue',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('미결정', '미결정'), ('선발', '선발'), ('미선발', '미선발')], default='미결정', max_length=5, null=True),
        ),
    ]
