# Generated by Django 3.0.6 on 2022-02-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0050_auto_20220221_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymembershipwithdrawalqueue',
            name='row_idx',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('미선발', '미선발'), ('선발', '선발'), ('미결정', '미결정')], default='미결정', max_length=5, null=True),
        ),
    ]
