# Generated by Django 3.0.6 on 2022-03-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applynsubmit', '0052_auto_20220221_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymembership',
            name='pf',
            field=models.CharField(blank=True, choices=[('미선발', '미선발'), ('선발', '선발'), ('미결정', '미결정')], default='미결정', max_length=5, null=True),
        ),
    ]
